### ISSUE TITLE
Server error if user applies a default tag manually

### ISSUE THREAD

**Issue by theopen-institute** [pfaffman/discourse-topic-default-tag#2]
I've got this plugin installed and working correctly (I think!), but I've been getting the following server error when a user tries to create a new post with a default tag manually applied:

> ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_topic_tags_on_topic_id_and_tag_id"
DETAIL:  Key (topic_id, tag_id)=(196, 28) already exists.
)
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.0.1/lib/patches/db/pg.rb:69:in `exec_params'

I tried to see if I could propose a pull request, but I'm afraid my very limited knowledge of Ruby would only make things worse. I believe a solution would be to check if a tag already exists on a new post before applying a default tag.

Thanks for sharing this great plugin!

**Comment by pfaffman** [comment]
Hey theopen. Glad this is *almost* working for you.

I applied an untested fix. Can you give it a shot and tell me if it works?

**Comment by pfaffman** [comment]
I didn't mean to close this.

**Comment by theopen-institute** [comment]
Seems to be working great! I'll post back if I encounter any unexpected behavior, but on 15 minutes of testing it seems to be fixed. Thanks again!

**Comment by pfaffman** [comment]
Great! That's quite a relief. I am pretty sure that's the fix (I should have written it that way to start, now that I think about it!). If it works at all, I'm fairly certain that we're safe.

Thanks for letting me know!
